#!/usr/bin/env bash

read -p "Are you sure? " -n 1 -r
echo

if [[ $REPLY =~ ^[Yy]$ ]]; then
  echo
  echo "Giving up doesnt always mean you are weak; sometimes it means that you are strong enough to let go."
  echo " " && sed -n '/Z/p' encoded | tail -n 6 | cut -c 8,22,23,41 && echo " "
else
  echo
  echo "Yeah, that's the spirit!"
fi
