#!/usr/bin/env bash
#
# Write down the commands you used to identify the murderer.

cd mystery

grep CLUE crimescene

grep Annabel people | grep -w F

cd streets

head -n 179 Buckingham_Place | tail -n 1

cd ../interviews

cat interview-699607

cd ..

grep -A 5 L337 vehicles | grep -B 2 -A 3 Blue | grep -B 1 -A 4 Honda | grep -B 4 -A 1 "6'"

cd memberships

cat AAA Delta_SkyMiles Terminal_City_Library Museum_of_Bash_History | grep -c "Jeremy Bowers"

cd ../..

./check "Jeremy Bowers"
